name: Automerge

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '* * * * *'

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://rkhan2104:${{secrets.GITHUB_TOKEN}}@https://github.com/rkhan2104/GrafanaTest/tree/main/test2

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: test2

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/rkhan2104/GrafanaTest/tree/main/test3

  # replace "master" with your master branch name
  MASTER_BRANCH: test3

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "rkhan2104@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
